# default-user-queue.yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"  # update this to your project namepsace
  name: "finetune-queue"
spec:
  clusterQueue: "all-compute-resources"
