# cluster-queue.yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 8
      - name: "memory"
        nominalQuota: 32Gi
  - coveredResources: ["nvidia.com/gpu"]
    flavors:
    - name: "on-demand"
      resources:
      - name: nvidia.com/gpu
        nominalQuota: 1   # Total GPUs available for scheduling
